### ISSUE TITLE
Add more options in spinner config (delay, opacity, background-color)

### ISSUE THREAD

**Issue by EmanJasarevic** [mpalourdio/ng-http-loader#25]
[Feature request/Enhancement]
Hi @mpalourdio and thanks for providing this module. :)

I am using it and I thought whether it will be possible to add more options in spinner configuration:
- **delay (time in ms after spinner will be shown)**. Currently it intercepts every requests and it is not so good for UX on small requests (< 100-200 ms).
- **css stylings**. Currently opacity is set to 0.7, background-color: "#f1f1f1". If it is possible it will be good to add more styling options (spinner placement, colors, etc.)

What do you think about this ones?

BR,
Eman

**Comment by mpalourdio** [comment]
Hi, 

thanks for feedback. Adding delay is not trivial at the moment, but that's something that I consider introducing in a near feature (PR are welcome :p). The problem is that deboucing (at RxJs level) with the current code will apply to BOTH show/hide actions. So I need to slightly refactor before introducing this option. (see the guilty code [here](https://github.com/mpalourdio/ng-http-loader/blob/19d0d1a3b892271516db9fc250aec40039862933/src/components/spinner/spinner.component.ts#L33-L37))

At the moment, you can exclude some url from firing the spinner (see documentation). It can fix some Ux problems for requests that you know they take very little time to process.

Considering adding CSS options (colors, positionning), I don't think I will do anything for the moment. Overriding styles is very easy at css level. And adding options, means adding maintenance.  

I want this module to be as simple as possible to consume.

Hope this is clear enough.

**Comment by EmanJasarevic** [comment]
Thanks for quick response and clarification. I think I can survive for now with excluding URLs, but I hope in one of future releases this feature will also be implemented. 
If I find more time I will participate as well :)

**Comment by mpalourdio** [comment]
I've just began a small implementation for the debounce feature. It's easier than expected. Just need to add tests. Could be okay later this week.

**Comment by mpalourdio** [comment]
Tracking the issue here : https://github.com/mpalourdio/ng-http-loader/issues/26

**Comment by mpalourdio** [comment]
@EmanJasarevic ``deboounceDelay`` has landed in v 0.6.0. See https://github.com/mpalourdio/ng-http-loader/blob/master/CHANGELOG.MD#changelog
