### ISSUE TITLE
Is it possible to change size and color?

### ISSUE THREAD

**Issue by ghiscoding** [mpalourdio/ng-http-loader#29]
Hello and thanks for the library, I was wondering if it's possible to change the size and/or color of the spinner? At first, I thought that I could use the [SASS files](https://github.com/tobiasahlin/SpinKit#scss) of SpinKit but you're actually not using SpinKit directly, so I guess it's out of the question. If I then read your homepage for [Customizing the Spinner](https://github.com/mpalourdio/ng-http-loader#customizing-the-spinner), it doesn't seem to have anything available for size or color and I didn't see such thing your code either. Do you have any suggestion in that regards?

**Comment by Albejr** [comment]
HTML
`<spinner backgroundColor="#4CAF50" spinner="sk-double-bounce"></spinner>`

CSS
`#spinner { background-color: #000 !important; }`

![image](https://user-images.githubusercontent.com/24717256/33506178-df604cf6-d6d5-11e7-8915-3c6db2c2debe.png)

**Comment by ghiscoding** [comment]
I thought the `backgroundColor` was for the backdrop? 

Following your advice on the CSS part, does that mean that I could overwrite with `!important` everywhere to resize a spinner? I would hope if there's an easier way, but if that works I might give that a try anyway (on Monday though).

**Comment by mpalourdio** [comment]
Hi !

Yes, the ``backgroundColor`` is the color of the spinner itself. I kept this name to be coherent with spinkit itself. See https://github.com/tobiasahlin/SpinKit/blob/fca79cdfea288767ac2cfbe0d654949ae77e6f84/css/spinners/6-chasing-dots.css#L24

For the size, it's not possible because it can be very tricky to do. If you take a look at [chasing-dots](https://github.com/tobiasahlin/SpinKit/blob/fca79cdfea288767ac2cfbe0d654949ae77e6f84/css/spinners/6-chasing-dots.css#L24) for example, it not only sets the size, but a ratio for the children.

For the moment, I'am sorry taht you can only do it at CSS level.

**Comment by mpalourdio** [comment]
I have just taken a quick look, and I am afraid taht it will not be possible. If I give the possibility to set main height and width, it will break for some components that define sizes at different places :

example for ``wandering-cubes`` :
[here](https://github.com/tobiasahlin/SpinKit/blob/master/css/spinners/4-wandering-cubes.css#L17-L18), [here](https://github.com/tobiasahlin/SpinKit/blob/master/css/spinners/4-wandering-cubes.css#L17-L18) for example :(

**Comment by ghiscoding** [comment]
Thanks a lot @mpalourdio for looking at this so quickly. Before I asked the question, I found [this](https://github.com/tobiasahlin/SpinKit/issues/118) on the SpinKit issue tracker and so it does seem possible to resize the spinner. SpinKit also has these [SASS variables](https://github.com/tobiasahlin/SpinKit/blob/master/scss/_variables.scss) which seems to default the size at 40px. I was thinking at first to use the SpinKit SASS to size it how I want, but you are using your css is that correct?

**Comment by mpalourdio** [comment]
Yes, I backported the css in the code of this module. The reason to not use directly the spinkit code is that angular cannot process css content in css files or in ``style`` tags.

CSS customization must be done with inline styles or via the API but that would be too much effort to maintain.

SASS has not been used because I didn't wan't libraries consumers to pre-process anything (So don't I). And to be honest, it's a matter of a few lines to override css.

**Comment by ghiscoding** [comment]
Thanks for the info @mpalourdio 

I guess it depends which library packager you use now, since I also have an open source library (Angular-Slickgrid) and with the first packager I tried, I had to write the CSS inline as you said. But I switched, not long after, to [ng-packagr](https://github.com/dherges/ng-packagr) and this one is built on top of `Angular-CLI` which also allows to use `styleUrls` and so external SASS and others do work with that packager. I use SASS in my lib for customization and it works with works will that packager. However, I'm not asking you to switch packager, I'm only writing this as an info for future project you might have.

Thanks again for the lib :)

**Comment by mpalourdio** [comment]
Thanks for those informations. I might give thi a try in the future. But for the moment, unfortunately, that's not something I will introduce.

**Comment by ghiscoding** [comment]
Side note, I changed the width and height of the spinner that I use with `!important` and this is enough to get me going.

Something like this works, it's not ideal but it works. 
```css
#spinner {
  opacity: .4 !important;
}
.sk-double-bounce {
  width: 60px !important;
  height: 60px !important;
}
```

So I guess that I'm ok with this patch and so I'll close the issue for now. You can always reference it if you ever want to add that functionality built in. Thanks again for all your efforts.

**Comment by mpalourdio** [comment]
So far, so good ! Thanks for those great feedbacks !
