### ISSUE TITLE
angular 6 compatibility

### ISSUE THREAD

**Issue by mpalourdio** [mpalourdio/ng-http-loader#62]
Adapt code so it's compatible with angular 6

**Comment by mpalourdio** [comment]
I hope I can give this a shot this weekend !

**Comment by mpalourdio** [comment]
WIP in https://github.com/mpalourdio/ng-http-loader/tree/ng6

**Comment by ghiscoding** [comment]
I would probably make it at least a Minor (semver) since it's more than a patch, and actually a Major might be a possibility too since Rx got bumped from 5 to 6. Are we able to still use your lib without using Angular 6? if the answer is no, then you need a Major, else a Minor is enough but I wouldn't do a Patch version

**Comment by mpalourdio** [comment]
Thanks for this valuable feedback, I totally agree with you. Two things won't be BC with any existing ng5 app :
-RxJs 6
- Minimum node version

As you said, a major version is needed here.

Thanks a lot.

**Comment by mpalourdio** [comment]
Angular 6 && RxJS 6 support has just landed in V1.0.0 \o/
